[package]
name = "url-shortener-rust"
version = "2.0.4"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "=0.5.0-rc.3"
rusqlite = "0.29.0"
log = "0.4"
env_logger = "0.10"