version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=/app/data/urls.db
      - RUST_LOG=info
    restart: unless-stopped