version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "7575:7575"
    volumes:
      - url_data:/app/data
    environment:
      - DATABASE_URL=/app/data/urls.db
      - RUST_LOG=info
    restart: unless-stopped

volumes:
  url_data: